---
title: "faceting, coordinate_flip() and theme()"
author: "Rashedul"
date: "7/2/2019"
output: 
  html_document: 
    keep_md: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## load libraries

```{r}
#install.packages("gapminder")
#install.packages("tidyverse")
library(tidyverse)
library(gapminder)
```

## check data

```{r}
head(gapminder)
```

## make scatter plot 

```{r}
ggplot(gapminder, aes(gdpPercap, lifeExp)) +
  geom_point()

```

## log transformation of values

```{r}
#
ggplot(gapminder, aes(gdpPercap, lifeExp)) +
  geom_point() +
  scale_x_log10()

# try another way
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point()
```

# change color

```{r}
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point(aes(color=continent))

#change sige of points
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point(aes(color=continent), size = 3)
```

# change some other parameters

```{r}
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point(pch=17, size=2, alpha= .8, aes(color=continent)) 

# what about this
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point(pch=17, size=2, alpha= .8, color= "red")

```

## use smoothing function

```{r}
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point() +
  geom_smooth()

# specify the method for smoothing
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point() +
  geom_smooth(lwd=2, se=FALSE, method="lm", col="blue")

# smooth by continent
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point() +
  geom_smooth(aes(color = continent))

# smooth by continent
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point(aes(color = continent)) +
  geom_smooth(aes(color = continent))
```

## example on faceting

```{r}
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point() +
  facet_wrap(~continent)

# change faceting  by column
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point() +
  facet_wrap(~continent, ncol=1)

# change faceting by row
ggplot(gapminder, aes(log10(gdpPercap), lifeExp)) +
  geom_point() +
  facet_wrap(~continent, nrow =1)
```


## voilin, boxplot and jitter

```{r}
#boxplot
ggplot(gapminder, aes(continent, lifeExp)) +
  geom_jitter() +
  geom_boxplot()

#color
ggplot(gapminder, aes(continent, lifeExp), fill = continent) +
  geom_jitter(alpha=1/2) +
  geom_boxplot()

#violin
ggplot(gapminder, aes(continent, lifeExp)) +
  geom_jitter() +
  geom_violin()

#color
ggplot(gapminder, aes(continent, lifeExp), fill = continent) +
  geom_jitter(alpha=1/2) +
  geom_violin()
```

## histograms

```{r}
ggplot(gapminder, aes(lifeExp)) +
  geom_histogram()

# change binsize
ggplot(gapminder, aes(lifeExp)) +
  geom_histogram(bins=50)

#
ggplot(gapminder, aes(lifeExp)) +
  geom_histogram(bins=100)

#
ggplot(gapminder, aes(lifeExp)) +
  geom_histogram(bins=500) 

# color by continent
ggplot(gapminder, aes(lifeExp)) + 
  geom_histogram(aes(color=continent))
```

## density plot

```{r}
ggplot(gapminder, aes(lifeExp)) + 
  geom_density()

# color
ggplot(gapminder, aes(lifeExp)) + 
  geom_density(aes(fill= "red"))

# change alpha
ggplot(gapminder, aes(lifeExp)) + 
  geom_density(aes(fill= "red"), alpha=1/4)

#
ggplot(gapminder, aes(lifeExp)) + 
  geom_density(aes(fill=continent), alpha=1/4)
```





